# Title: This appears on your metadata and is part of your title tag
# ===========
title: Mark Deanil Vicente

# Description: This is part of your metatag, keep it under 150 characters for SEO
# =========== 
description: "This is my personal blog website."

# Avatar path: The path to your avatar image
# ===========
avatar_path: "/assets/img/avatar.png"

plugins:
  - jekyll-feed

# Url: Your hosting url
# Change this to your hosting url e.g. http://[your_name].github.io OR http://localhost:4000
# ===========
url: "https://deanilvincent.github.io/"

# Google Tag manager ID: Use Google Tag manager to easily manage your tracking scripts.  
# Create a new container and add your container ID here
# ==========
tagManagerID: GTM-TJZQLSK # Your tag manager container ID

# Disqus settings: For comment support
# ==========
disqus_shortname: deanilvincent-github-io # Disqus shortname

# Contact form post url - Where the form gets posted - Check out formspree.io for free form posts http://formspree.io/
# ==========
formpost: http://formspree.io/markdeanilvicente@gmail.com

env: production # - Set 'development' or 'production'
exclude: [node_modules/, .sass-cache/]

# Adding gems
plugins: [jekyll-paginate]

sass:
 sass_dir: _sass
 style: compressed

paginate: 5
paginate_path: "blog/:num"

# Build settings
markdown: kramdown
permalink: pretty

baseurl: ""